
#include "Arduino.h"

// Arduino sketch playing arpeggios generated by LFSR generated polynomials combinations converging to symmetrical fractal chords

// Define the pins for the speaker, the buttons and the knob
#define SPEAKER_PIN 9
#define GENERATE_PIN 2 // Button to generate a new sequence
#define EVOLVE_PIN 3 // Button to evolve the current sequence
#define REPEAT_PIN 4 // Button to repeat the current sequence
#define KNOB_PIN PIN_A0 // Knob to set the target function

// Define frequencies for each note used (in Hz)
const float C4 = 261.63;
const float Db4 = 277.18;
const float D4 = 293.66;
const float Eb4 = 311.13;
const float E4 = 329.63;
const float F4 = 349.23;
const float Gb4 = 369.99;
const float G4 = 392.00;
const float Ab4 = 415.30;
const float A4 = 440.00;
const float Bb4 = 466.16;
const float B4 = 493.88;
const float C5 = 523.25;
const float Db5 = 554.37;
const float D5 = 587.33;
const float Eb5 = 622.25;
const float E5 = 659.26;
const float F5 = 698.46;
const float Gb5 = 739.99;
const float G5 = 783.99;
const float Ab5 = 830.61;
const float A5 = 880.00;
const float Bb5 = 932.33;
const float B5 = 987.77;
const float C6 = 1046.50;
const float Db6 = 1108.73;
const float D6 = 1174.66;
const float Eb6 = 1244.51;
const float E6 = 1318.51;
const float F6 = 1396.91;
const float Gb6 = 1479.98;
const float G6 = 1567.98;
const float Ab6 = 1661.22;
const float A6 = 1760.00;
const float Bb6 = 1864.66;
const float B6 = 1975.53;
const float C7 = 2093.00;

// Define the duration of each note in milliseconds
#define NOTE_DURATION 100

// Define the LFSR parameters
#define LFSR_SEED 0xACE1 // Initial state of the LFSR
#define LFSR_MASK 0xB400 // Polynomial mask for the LFSR

// Define the number of polynomials to combine
#define POLY_COUNT 3

// Define the number of iterations to converge to a fractal chord
#define ITER_COUNT 5

// Define the number of harmonizing jazz progressions
#define PROG_COUNT 32

// Target chord notes for each progression index
float target_freqs[PROG_COUNT] = {
  C4, D4, E4, F4, G4, A4, B4, C5,
  C5, Db5, D5, Eb5, E5, F5, Gb5, G5,
  G5, Ab5, A5, Bb5, B5, C6, Db6, D6,
  D6, Eb6, E6, F6, Gb6, G6, Ab6, A6
};

// Declare a global variable to store the current state of the LFSR
uint16_t lfsr = LFSR_SEED;

// Declare an array to store the polynomials for each arpeggio
uint16_t polys[POLY_COUNT];

// Declare an array to store the notes for each polynomial
uint16_t notes[POLY_COUNT];

// Declare an array to store the frequencies for each note
float freqs_scale[] = {C4, D4, E4, F4, G4, A4, B4, C5};

uint8_t currentProgIndex = 0;

// Declare a function to generate a random bit using the LFSR
uint8_t lfsr_bit() {
  lfsr >>= 1;
  if (lfsr & 1) {
    lfsr ^= LFSR_MASK;
    return 1;
  }
  return 0;
}

// Declare a function to generate a random note using the LFSR
uint16_t lfsr_note() {
  uint8_t index = 0;
  index += lfsr_bit();
  index += lfsr_bit() << 1;
  index += lfsr_bit() << 2;
  return (uint16_t)freqs_scale[index % 8];
}

// Declare a function to generate a polynomial using the LFSR
uint16_t lfsr_poly() {
  uint16_t poly = 0;
  for (int i=0; i<8; i++) {
    poly |= (lfsr_bit() << i);
  }
  return poly;
}

// Evaluate a polynomial using iterative fractal mapping z -> z^2 + c
uint16_t eval_poly(uint16_t poly, uint16_t note) { 
   uint32_t z = note;
   uint32_t c = poly;
   for (uint8_t i = 0; i < 3; i++) {
      z = (z * z) % (uint16_t)C5;
      z = (z + c) % (uint16_t)C5;
   } 
   return (uint16_t)(z % (uint16_t)C5);
}

// Declare a function to play a note at a given frequency and duration 
void play_note(uint16_t frequency, uint16_t duration) { 
   if (frequency < 100) frequency += 200; // Audibility check
   tone(SPEAKER_PIN, frequency, duration);
   delay(duration); 
   noTone(SPEAKER_PIN);
}

// Symmetrical arpeggio forward and backward
void play_arpeggio(uint16_t poly, uint16_t note) {
  uint16_t sequence[8];
  uint16_t current = note;
  for (uint8_t i = 0; i < 8; i++) {
    sequence[i] = current;
    current = eval_poly(poly, current);
  }
  for (uint8_t i = 0; i < 8; i++) {
    play_note(sequence[i], NOTE_DURATION);
  }
  for (int8_t i = 6; i >= 0; i--) {
    play_note(sequence[i], NOTE_DURATION);
  }
}

// Play fractal chord as a note sum
void play_fractal(uint16_t polys_arr[], uint16_t notes_arr[]) {
  uint16_t sum = 0;
  for (uint8_t i = 0; i < POLY_COUNT; i++) {
    sum += eval_poly(polys_arr[i], notes_arr[i]);
  }
  play_note(sum, NOTE_DURATION * 4);
}

// Generate new random sequence
void generate_sequence() {
  for (uint8_t i = 0; i < POLY_COUNT; i++) {
    polys[i] = lfsr_poly();
    notes[i] = lfsr_note();
  }
}

// Evolution toward the target note for the current progression index
void evolve_sequence() {
  for (uint8_t i = 0; i < POLY_COUNT; i++) {
    uint16_t current_val = eval_poly(polys[i], notes[i]);
    float target_freq = target_freqs[currentProgIndex];
    float min_diff = abs(target_freq - current_val);
    
    // Check bit-flips to find closer match to target note
    for (int b = 0; b < 8; b++) {
      uint16_t next_poly = polys[i] ^ (1 << b);
      uint16_t next_val = eval_poly(next_poly, notes[i]);
      if (abs(target_freq - next_val) < min_diff) {
        polys[i] = next_poly;
        min_diff = abs(target_freq - next_val);
      }
    }
  }
}

// Play full sequence
void play_sequence() {
  for (uint8_t i = 0; i < ITER_COUNT; i++) {
    for (uint8_t j = 0; j < POLY_COUNT; j++) {
      play_arpeggio(polys[j], notes[j]);
    }
    play_fractal(polys, notes);
    for (uint8_t j = 0; j < POLY_COUNT; j++) {
      notes[j] = eval_poly(polys[j], notes[j]);
    }
  }
}

// Read knob to set progression index
void set_target() {
  uint16_t value = analogRead(KNOB_PIN);
  uint8_t index = map(value, 0, 1023, 0, PROG_COUNT - 1);
  currentProgIndex = index;
  
  if (index % (PROG_COUNT / 4) == 0) {
    digitalWrite(LED_BUILTIN, HIGH);
  } else {
    digitalWrite(LED_BUILTIN, LOW);
  }
}

void setup() {
  pinMode(SPEAKER_PIN, OUTPUT);
  pinMode(GENERATE_PIN, INPUT_PULLUP);
  pinMode(EVOLVE_PIN, INPUT_PULLUP);
  pinMode(REPEAT_PIN, INPUT_PULLUP);
  pinMode(KNOB_PIN, INPUT);
  pinMode(LED_BUILTIN, OUTPUT);
  Serial.begin(9600);
}

void loop() {
  set_target();
  if (digitalRead(GENERATE_PIN) == LOW) {
    generate_sequence();
    play_sequence();
    delay(1000);
  }
  if (digitalRead(EVOLVE_PIN) == LOW) {
    evolve_sequence();
    play_sequence();
    delay(1000);
  }
  if (digitalRead(REPEAT_PIN) == LOW) {
    play_sequence();
    delay(1000);
  }
}
