
#include "Arduino.h"

// Arduino sketch playing arpeggios generated by LFSR generated polynomials combinations converging to symmetrical fractal chords

// Define the pins for the speaker and the buttons
#define SPEAKER_PIN 9
#define GENERATE_PIN 2 // Button to generate a new sequence
#define EVOLVE_PIN 3 // Button to evolve the current sequence
#define REPEAT_PIN 4 // Button to repeat the current sequence

// Define the notes and frequencies for the arpeggios
#define C4 262
#define D4 294
#define E4 330
#define F4 349
#define G4 392
#define A4 440
#define B4 494
#define C5 523

// Define the duration of each note in milliseconds
#define NOTE_DURATION 100

// Define the LFSR parameters
#define LFSR_SEED 0xACE1 // Initial state of the LFSR
#define LFSR_MASK 0xB400 // Polynomial mask for the LFSR

// Define the number of polynomials to combine
#define POLY_COUNT 3

// Define the number of iterations to converge to a fractal chord
#define ITER_COUNT 5

// Define the target chord frequencies (Cmaj7 approximation)
const uint16_t target_chord[] = {C4, E4, G4, B4};
#define TARGET_COUNT 4

// Declare a global variable to store the current state of the LFSR
uint16_t lfsr = LFSR_SEED;

// Declare an array to store the polynomials for each arpeggio
uint16_t polys[POLY_COUNT];

// Declare an array to store the notes for each polynomial
uint16_t notes[POLY_COUNT];

// Declare an array to store the frequencies for each note
uint16_t freqs_arr[] = {C4, D4, E4, F4, G4, A4, B4, C5};

// Declare a function to generate a random bit using the LFSR
uint8_t lfsr_bit() {
  lfsr >>= 1;
  if (lfsr & 1) {
    lfsr ^= LFSR_MASK;
    return 1;
  }
  return 0;
}

// Declare a function to generate a random note using the LFSR
uint16_t lfsr_note() {
  uint8_t index = 0;
  index += lfsr_bit();
  index += lfsr_bit() << 1;
  index += lfsr_bit() << 2;
  return freqs_arr[index % 8];
}

// Declare a function to generate a polynomial using the LFSR
uint16_t lfsr_poly() {
  uint16_t poly = 0;
  for (int i=0; i<8; i++) {
    poly |= (lfsr_bit() << i);
  }
   return poly; 
}

// Evaluate a polynomial at a given note z0 using Mandelbrot-style iteration
// f(z) = z^2 + c where c is the polynomial representation.
// Modulo C5 to keep it in audible range.
uint16_t eval_poly(uint16_t poly, uint16_t note) { 
   uint32_t z = note;
   uint32_t c = poly;
   // Small number of iterations for fractal property
   for (uint8_t i = 0; i < 3; i++) {
      z = (z * z) % C5;
      z = (z + c) % C5;
   } 
   return (uint16_t)(z % C5);
}

// Declare a function to play a note at a given frequency and duration 
void play_note(uint16_t frequency, uint16_t duration) { 
   if (frequency < 50) frequency += 200; // Audibility check
   tone(SPEAKER_PIN, frequency, duration);
   delay(duration); 
   noTone(SPEAKER_PIN);
}

// Plays an arpeggio "symmetrically" (forward and backward)
void play_arpeggio(uint16_t poly, uint16_t note) {
  uint16_t sequence[8];
  uint16_t current = note;
  for (uint8_t i = 0; i < 8; i++) {
    sequence[i] = current;
    current = eval_poly(poly, current);
  }
  // Symmetrical play
  for (uint8_t i = 0; i < 8; i++) {
    play_note(sequence[i], NOTE_DURATION);
  }
  for (int8_t i = 6; i >= 0; i--) {
    play_note(sequence[i], NOTE_DURATION);
  }
}

// Declare a function to play a fractal chord using a given array of polynomials and notes
void play_fractal(uint16_t polys_arr[], uint16_t notes_arr[]) {
  uint16_t sum = 0;
  for (uint8_t i = 0; i < POLY_COUNT; i++) {
    sum += eval_poly(polys_arr[i], notes_arr[i]);
  }
  play_note(sum, NOTE_DURATION * 4);
}

// Declare a function to generate a sequence of arpeggios and fractal chords
void generate_sequence() {
  for (uint8_t i = 0; i < POLY_COUNT; i++) {
    polys[i] = lfsr_poly();
    notes[i] = lfsr_note();
  }
}

// Evolution rule toward matching chord notes in the target_chord
void evolve_sequence() {
  for (uint8_t i = 0; i < POLY_COUNT; i++) {
    uint16_t current_val = eval_poly(polys[i], notes[i]);
    // Find nearest target frequency
    uint16_t target = target_chord[0];
    uint16_t min_diff = abs(target - current_val);
    for(int t=1; t<TARGET_COUNT; t++) {
        uint16_t d = abs(target_chord[t] - current_val);
        if (d < min_diff) {
            min_diff = d;
            target = target_chord[t];
        }
    }
    
    // Bit-flip evolution to reduce distance to nearest target chord frequency
    for (int b = 0; b < 8; b++) {
      uint16_t next_poly = polys[i] ^ (1 << b);
      uint16_t next_val = eval_poly(next_poly, notes[i]);
      if (abs(target - next_val) < min_diff) {
        polys[i] = next_poly;
        min_diff = abs(target - next_val);
      }
    }
  }
}

// Play the generated sequence
void play_sequence() {
  for (uint8_t i = 0; i < ITER_COUNT; i++) {
    for (uint8_t j = 0; j < POLY_COUNT; j++) {
      play_arpeggio(polys[j], notes[j]);
    }
    play_fractal(polys, notes);
    for (uint8_t j = 0; j < POLY_COUNT; j++) {
      notes[j] = eval_poly(polys[j], notes[j]);
    }
  }
}

void setup() {
  pinMode(SPEAKER_PIN, OUTPUT);
  pinMode(GENERATE_PIN, INPUT_PULLUP);
  pinMode(EVOLVE_PIN, INPUT_PULLUP);
  pinMode(REPEAT_PIN, INPUT_PULLUP);
  Serial.begin(9600);
}

void loop() {
  if (digitalRead(GENERATE_PIN) == LOW) {
    generate_sequence();
    play_sequence();
    delay(1000);
  }
  if (digitalRead(EVOLVE_PIN) == LOW) {
    evolve_sequence();
    play_sequence();
    delay(1000);
  }
  if (digitalRead(REPEAT_PIN) == LOW) {
    play_sequence();
    delay(1000);
  }
}
