
#include "Arduino.h"

// Arduino sketch playing arpeggios generated by LFSR generated polynomials combinations converging to symmetrical fractal chords

// Define the pins for the speaker and the buttons
#define SPEAKER_PIN 9
#define GENERATE_PIN 2 // Button to generate a new sequence
#define EVOLVE_PIN 3 // Button to evolve the current sequence
#define REPEAT_PIN 4 // Button to repeat the current sequence

// Define the notes and frequencies for the arpeggios
#define C4 262
#define D4 294
#define E4 330
#define F4 349
#define G4 392
#define A4 440
#define B4 494
#define C5 523

// Define the duration of each note in milliseconds
#define NOTE_DURATION 100

// Define the LFSR parameters
#define LFSR_SEED 0xACE1 // Initial state of the LFSR
#define LFSR_MASK 0xB400 // Polynomial mask for the LFSR

// Define the number of polynomials to combine
#define POLY_COUNT 3

// Define the number of iterations to converge to a fractal chord
#define ITER_COUNT 5

// Define the learning rate for gradient descent
#define LEARNING_RATE 0.01

// Define the jazz chord progressions as a target function
#define TARGET_FUNCTION(x) (C4 + E4 + G4 + B4) * sin(x)

// Declare a global variable to store the current state of the LFSR
uint16_t lfsr = LFSR_SEED;

// Declare an array to store the polynomials for each arpeggio
uint16_t polys[POLY_COUNT];

// Declare an array to store the notes for each polynomial
uint16_t notes[POLY_COUNT];

// Declare an array to store the frequencies for each note
uint16_t freqs_arr[] = {C4, D4, E4, F4, G4, A4, B4, C5};

// Declare a function to generate a random bit using the LFSR
uint8_t lfsr_bit() {
  lfsr >>= 1;
  if (lfsr & 1) {
    lfsr ^= LFSR_MASK;
    return 1;
  }
  return 0;
}

// Declare a function to generate a random note using the LFSR
uint16_t lfsr_note() {
  uint8_t index = 0;
  index += lfsr_bit();
  index += lfsr_bit() << 1;
  index += lfsr_bit() << 2;
  return freqs_arr[index % 8];
}

// Declare a function to generate a polynomial using the LFSR
uint16_t lfsr_poly() {
  uint16_t poly = 0;
  for (int i=0; i<8; i++) {
    poly |= (lfsr_bit() << i);
  }
   return poly; 
}

// Declare a function to evaluate a polynomial at a given note 
uint16_t eval_poly(uint16_t poly, uint16_t note) { 
   uint32_t result = note;
   for (uint8_t i = 0; i < 8; i++) {
      if (poly & (1 << i)) { 
         // MODULO AT EACH STEP to prevent overflow and keep values in audible range
         result = (result * result) % C5;
         result = (result + note) % C5;
      } 
   } 
   return (uint16_t)(result % C5);
}

// Declare a function to play a note at a given frequency and duration 
void play_note(uint16_t frequency, uint16_t duration) { 
   tone(SPEAKER_PIN, frequency, duration);
   delay(duration); 
   noTone(SPEAKER_PIN);
}

// Declare a function to play an arpeggio using a given polynomial and note
void play_arpeggio(uint16_t poly, uint16_t note) {
  uint16_t current = note;
  for (uint8_t i = 0; i < 8; i++) {
    play_note(current, NOTE_DURATION);
    Serial.print(current);
    Serial.print(",");
    Serial.println(NOTE_DURATION);
    current = eval_poly(poly, current);
  }
}

// Declare a function to play a fractal chord using a given array of polynomials and notes
void play_fractal(uint16_t polys_arr[], uint16_t notes_arr[]) {
  uint16_t sum = 0;
  for (uint8_t i = 0; i < POLY_COUNT; i++) {
    sum += eval_poly(polys_arr[i], notes_arr[i]);
  }
  play_note(sum, NOTE_DURATION * 8);
  Serial.print(sum);
  Serial.print(",");
  Serial.println(NOTE_DURATION * 8);
}

// Declare a function to generate a sequence of arpeggios and fractal chords
void generate_sequence() {
  for (uint8_t i = 0; i < POLY_COUNT; i++) {
    polys[i] = lfsr_poly();
    notes[i] = lfsr_note();
  }
}

// Declare a function to evolve a sequence of arpeggios and fractal chords using gradient descent
void evolve_sequence() {
  for (uint8_t i = 0; i < POLY_COUNT; i++) {
    uint16_t current_val = eval_poly(polys[i], notes[i]);
    uint16_t target_val = (uint16_t)abs(TARGET_FUNCTION(notes[i]));
    float error = (float)target_val - current_val;
    
    // Finite difference approximation for gradient
    // We can check the effect of toggling bits in the polynomial
    for (int b = 0; b < 8; b++) {
      uint16_t next_poly = polys[i] ^ (1 << b);
      uint16_t next_val = eval_poly(next_poly, notes[i]);
      float next_error = (float)target_val - next_val;

      // If flipping the bit reduces the error, keep it
      if (abs(next_error) < abs(error)) {
        polys[i] = next_poly;
        error = next_error;
      }
    }
  }
}

// Declare a function to play a sequence of arpeggios and fractal chords
void play_sequence() {
  for (uint8_t i = 0; i < ITER_COUNT; i++) {
    for (uint8_t j = 0; j < POLY_COUNT; j++) {
      play_arpeggio(polys[j], notes[j]);
    }
    play_fractal(polys, notes);
    for (uint8_t j = 0; j < POLY_COUNT; j++) {
      notes[j] = eval_poly(polys[j], notes[j]);
      if (notes[j] < 100) notes[j] += 100; // Keep it audible
    }
  }
}

// Setup function to run once at the beginning
void setup() {
  pinMode(SPEAKER_PIN, OUTPUT);
  pinMode(GENERATE_PIN, INPUT_PULLUP);
  pinMode(EVOLVE_PIN, INPUT_PULLUP);
  pinMode(REPEAT_PIN, INPUT_PULLUP);
  Serial.begin(9600);
}

// Loop function to run repeatedly
void loop() {
  if (digitalRead(GENERATE_PIN) == LOW) {
    generate_sequence();
    play_sequence();
    delay(1000);
  }
  if (digitalRead(EVOLVE_PIN) == LOW) {
    evolve_sequence();
    play_sequence();
    delay(1000);
  }
  if (digitalRead(REPEAT_PIN) == LOW) {
    play_sequence();
    delay(1000);
  }
}
